### ISSUE TITLE
Peer Review (Lea)

### ISSUE THREAD

**Issue by lfrank14** [ajfridman/EDLD610_FinalProject#1]
(a) Areas of strength
+ What a fun dataset to work with. It makes me regret using my boring task data..
+ I really like that you added the different world regions to the data. 
+ I'm having a hard time deciding which version of Figure 1 I like better, but I think I'm leaning towards the second version with the N averaged by regions because it's a little easier to see a pattern. I also really like the transparent bars, I did something similar in my figures. It easier to estimate the values of each bar in comparison to the grid lines.
+ I really like the annotation of the total points in Figure 2 and that you summarized by region.
+ I think you should definitely go with that second version of Figure 3. I think it's a really interesting way to visualize the difference between the two types of coffee. Although I wrote that before I saw version 3. This one is also nice in that it gives you a point of reference for no difference.

(b) Things I learned
+ I don't think I've ever seen anyone visualize the difference between two variables like in version 2 of Figure 3, but it's much cleaner than the dodged bar plots. Same with version 3. 

(c) Areas for improvement
+ Something I picked up from reviewing portfolios is that you can use mutate_at(c([var names), as.factor()) to convert multiple variables into factors in a single line
+ I think the dissociation between figure 1 and 2 is really interesting, even though Oceania doesn't produce much coffee that gets reviewed, it's still among the highest points received. If you combine the figures somehow to show that dissociation it could make for a really strong point.
+ the code for figure 3 is throwing me an error. You're selecting everything but the county and year for the coffee_species data frame, but there's no year variable in the coffee data frame. I just removed that argument from the select() function and it ran fine.
+ You could also try looking at relationships between the different quality metrics. You could do some scatter plots and scale by region or something.

**Comment by lfrank14** [comment]
@datalorax

**Comment by datalorax** [comment]
Thanks Lea, this some great feedback.

When using `mutate_at` you can also use the optional `vars` and `funs` arguments.

Andrew - please review the error Lea was getting carefully. This is a really important piece of reproducibility. 

Really good suggestions, Lea!
